# Generated by Django 3.2.12 on 2023-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20231214_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('caseno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('offense', models.CharField(max_length=50)),
                ('submitingofficername', models.CharField(blank=True, default='user', max_length=50)),
                ('submitingofficerid', models.CharField(max_length=50)),
                ('victim', models.CharField(max_length=50)),
                ('suspect', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(max_length=50)),
                ('seizure', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'usercasedetails',
            },
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
