# Generated by Django 5.0.2 on 2024-02-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_usersession_delete_casedetails_delete_userdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
